parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: null
    database_name: mybiz
    database_user: root
    database_password: null
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: f51e391b70109a39914f95631448a36fa
    database_path: null
    application_name: MyBiz
    customer_name: testklant
    jquery_mobile_theme: c
