# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal

_welcome:
    pattern:  /
    defaults: { _controller: PortalBundle:Welcome:index }

_login:
    pattern:   /secured/login
    defaults:  { _controller: UserSecurityBundle:Security:login }

_login_check:
    pattern:   /secured/login_check
