# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal

_front:
    pattern:  /
    defaults: { _controller: UserSecurityBundle:Security:login }

_login:
    resource: "@UserSecurityBundle/Controller/SecurityController.php"
    type:     annotation
    prefix:   /secured

_admin:
    resource: "@AdminBundle/Controller/IndexController.php"
    type:     annotation
    prefix:   /secured/admin

_setup:
    resource: "@AdminBundle/Controller/Setup/SetupController.php"
    type:     annotation
    prefix:   /secured/admin/setup

_prospects:
    resource: "@AdminBundle/Controller/Contacts/ProspectController.php"
    type:     annotation
    prefix:   /secured/admin/contacts/prospects